# Dockerfile для Telegram-бота
FROM python:3.12-slim

RUN mkdir /bot

WORKDIR /bot

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# CMD ["python", "telegram_bot/bot.py"]

CMD ["python", "-m", "telegram_bot.bot"]